version: "3.9"

services:
  app:
    build: .
    container_name: socratic-app
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: socratic-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: socratic
      POSTGRES_USER: socratic
      POSTGRES_PASSWORD: socratic
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U socratic"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
